<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLqkiSSN\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLqkiSSN/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLqkiSSN.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLqkiSSN\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerLqkiSSN\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'LqkiSSN',
    'container.build_id' => 'f4b68158',
    'container.build_time' => 1540982923,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLqkiSSN');
