<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVyM5d94\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVyM5d94/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVyM5d94.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVyM5d94\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerVyM5d94\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'VyM5d94',
    'container.build_id' => 'beea5b32',
    'container.build_time' => 1540972776,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVyM5d94');
